import { ArchNodeType } from '../types/node-types';

// Simplified type - just a record mapping node types to their default properties
export const NODE_DEFAULTS: Record<ArchNodeType, Record<string, unknown>> = {
  [ArchNodeType.CDN]: {
    nodeType: ArchNodeType.CDN,
    maxRPS: 100000,
    baseLatencyMs: 5,
    latencyStdDevMs: 2,
    failureRate: 0.001,
    maxConcurrentRequests: 50000,
    cacheHitRate: 0.9,
    regions: ['us-east-1'],
  },
  [ArchNodeType.LOAD_BALANCER]: {
    nodeType: ArchNodeType.LOAD_BALANCER,
    maxRPS: 50000,
    baseLatencyMs: 2,
    latencyStdDevMs: 1,
    failureRate: 0.0005,
    maxConcurrentRequests: 25000,
    algorithm: 'round_robin',
    healthCheckIntervalMs: 5000,
  },
  [ArchNodeType.FRONTEND]: {
    nodeType: ArchNodeType.FRONTEND,
    maxRPS: 10000,
    baseLatencyMs: 15,
    latencyStdDevMs: 5,
    failureRate: 0.005,
    maxConcurrentRequests: 5000,
    instances: 3,
    cpuPerInstance: 2,
    memoryPerInstanceMB: 2048,
    autoScale: true,
    autoScaleThreshold: 70,
  },
  [ArchNodeType.API_GATEWAY]: {
    nodeType: ArchNodeType.API_GATEWAY,
    maxRPS: 20000,
    baseLatencyMs: 10,
    latencyStdDevMs: 3,
    failureRate: 0.002,
    maxConcurrentRequests: 10000,
    rateLimitRPS: 15000,
    authEnabled: true,
    corsEnabled: true,
  },
  [ArchNodeType.AUTH_SERVICE]: {
    nodeType: ArchNodeType.AUTH_SERVICE,
    maxRPS: 5000,
    baseLatencyMs: 25,
    latencyStdDevMs: 10,
    failureRate: 0.01,
    maxConcurrentRequests: 2000,
    instances: 2,
    cpuPerInstance: 2,
    memoryPerInstanceMB: 1024,
    autoScale: true,
    autoScaleThreshold: 75,
  },
  [ArchNodeType.ORDER_SERVICE]: {
    nodeType: ArchNodeType.ORDER_SERVICE,
    maxRPS: 3000,
    baseLatencyMs: 50,
    latencyStdDevMs: 20,
    failureRate: 0.01,
    maxConcurrentRequests: 1500,
    instances: 3,
    cpuPerInstance: 4,
    memoryPerInstanceMB: 2048,
    autoScale: true,
    autoScaleThreshold: 70,
  },
  [ArchNodeType.CUSTOM_SERVICE]: {
    nodeType: ArchNodeType.CUSTOM_SERVICE,
    maxRPS: 5000,
    baseLatencyMs: 30,
    latencyStdDevMs: 10,
    failureRate: 0.01,
    maxConcurrentRequests: 2000,
    instances: 2,
    cpuPerInstance: 2,
    memoryPerInstanceMB: 1024,
    autoScale: false,
    autoScaleThreshold: 80,
  },
  [ArchNodeType.DATABASE]: {
    nodeType: ArchNodeType.DATABASE,
    maxRPS: 2000,
    baseLatencyMs: 5,
    latencyStdDevMs: 3,
    failureRate: 0.005,
    maxConcurrentRequests: 500,
    dbType: 'postgresql',
    maxConnections: 100,
    readReplicas: 0,
    avgQueryLatencyMs: 5,
    connectionPoolSize: 20,
  },
  [ArchNodeType.CACHE]: {
    nodeType: ArchNodeType.CACHE,
    maxRPS: 50000,
    baseLatencyMs: 1,
    latencyStdDevMs: 0.5,
    failureRate: 0.001,
    maxConcurrentRequests: 20000,
    cacheType: 'redis',
    maxMemoryMB: 1024,
    hitRate: 0.85,
    ttlSeconds: 300,
    evictionPolicy: 'lru',
  },
  [ArchNodeType.QUEUE]: {
    nodeType: ArchNodeType.QUEUE,
    maxRPS: 10000,
    baseLatencyMs: 3,
    latencyStdDevMs: 1,
    failureRate: 0.002,
    maxConcurrentRequests: 5000,
    queueType: 'kafka',
    maxQueueDepth: 100000,
    consumerCount: 3,
    consumerProcessingMs: 50,
    partitions: 6,
  },
  [ArchNodeType.WEBSOCKET_SERVER]: {
    nodeType: ArchNodeType.WEBSOCKET_SERVER,
    maxRPS: 50000,
    baseLatencyMs: 2,
    latencyStdDevMs: 1,
    failureRate: 0.001,
    maxConcurrentRequests: 100000,
    instances: 4,
    cpuPerInstance: 4,
    memoryPerInstanceMB: 4096,
    autoScale: true,
    autoScaleThreshold: 80,
    maxConnections: 10000,
  },
  [ArchNodeType.SEARCH_ENGINE]: {
    nodeType: ArchNodeType.SEARCH_ENGINE,
    maxRPS: 5000,
    baseLatencyMs: 50,
    latencyStdDevMs: 20,
    failureRate: 0.005,
    maxConcurrentRequests: 2000,
    engineType: 'elasticsearch',
    maxMemoryMB: 8192,
    shardCount: 5,
    replicaCount: 1,
    indexingLatencyMs: 100,
  },
  [ArchNodeType.STREAM_PROCESSOR]: {
    nodeType: ArchNodeType.STREAM_PROCESSOR,
    maxRPS: 10000,
    baseLatencyMs: 20,
    latencyStdDevMs: 10,
    failureRate: 0.003,
    maxConcurrentRequests: 5000,
    processorType: 'kafka-streams',
    instances: 3,
    cpuPerInstance: 8,
    memoryPerInstanceMB: 4096,
    autoScale: true,
    autoScaleThreshold: 80,
    processLatencyMs: 200,
  },
  [ArchNodeType.ML_MODEL_SERVICE]: {
    nodeType: ArchNodeType.ML_MODEL_SERVICE,
    maxRPS: 2000,
    baseLatencyMs: 150,
    latencyStdDevMs: 50,
    failureRate: 0.01,
    maxConcurrentRequests: 500,
    instances: 2,
    cpuPerInstance: 8,
    memoryPerInstanceMB: 8192,
    autoScale: true,
    autoScaleThreshold: 75,
    gpuSupport: true,
    inferenceLatencyMs: 150,
  },
  [ArchNodeType.PAYMENT_GATEWAY]: {
    nodeType: ArchNodeType.PAYMENT_GATEWAY,
    maxRPS: 5000,
    baseLatencyMs: 300,
    latencyStdDevMs: 100,
    failureRate: 0.005,
    maxConcurrentRequests: 1000,
    provider: 'stripe',
    instances: 3,
    cpuPerInstance: 4,
    memoryPerInstanceMB: 2048,
    transactionLatencyMs: 300,
  },
  [ArchNodeType.NOTIFICATION_SERVICE]: {
    nodeType: ArchNodeType.NOTIFICATION_SERVICE,
    maxRPS: 10000,
    baseLatencyMs: 50,
    latencyStdDevMs: 20,
    failureRate: 0.01,
    maxConcurrentRequests: 5000,
    instances: 3,
    cpuPerInstance: 2,
    memoryPerInstanceMB: 1024,
    autoScale: true,
    autoScaleThreshold: 80,
    channels: ['email', 'sms', 'push'],
  },
  [ArchNodeType.ANALYTICS_SERVICE]: {
    nodeType: ArchNodeType.ANALYTICS_SERVICE,
    maxRPS: 5000,
    baseLatencyMs: 100,
    latencyStdDevMs: 50,
    failureRate: 0.005,
    maxConcurrentRequests: 2000,
    instances: 2,
    cpuPerInstance: 4,
    memoryPerInstanceMB: 4096,
    autoScale: false,
    autoScaleThreshold: 80,
    dataWarehouse: 'bigquery',
    aggregationLatencyMs: 500,
  },
  [ArchNodeType.REAL_TIME_DB]: {
    nodeType: ArchNodeType.REAL_TIME_DB,
    maxRPS: 20000,
    baseLatencyMs: 10,
    latencyStdDevMs: 5,
    failureRate: 0.002,
    maxConcurrentRequests: 10000,
    dbType: 'firebase',
    maxMemoryMB: 4096,
    maxConnections: 5000,
    replicationLatencyMs: 50,
  },
};

export const NODE_LABELS: Record<ArchNodeType, string> = {
  [ArchNodeType.CDN]: 'CDN',
  [ArchNodeType.LOAD_BALANCER]: 'Load Balancer',
  [ArchNodeType.FRONTEND]: 'Frontend',
  [ArchNodeType.API_GATEWAY]: 'API Gateway',
  [ArchNodeType.AUTH_SERVICE]: 'Auth Service',
  [ArchNodeType.ORDER_SERVICE]: 'Order Service',
  [ArchNodeType.CUSTOM_SERVICE]: 'Custom Service',
  [ArchNodeType.DATABASE]: 'Database',
  [ArchNodeType.CACHE]: 'Cache',
  [ArchNodeType.QUEUE]: 'Message Queue',
  [ArchNodeType.WEBSOCKET_SERVER]: 'WebSocket Server',
  [ArchNodeType.SEARCH_ENGINE]: 'Search Engine',
  [ArchNodeType.STREAM_PROCESSOR]: 'Stream Processor',
  [ArchNodeType.ML_MODEL_SERVICE]: 'ML Model Service',
  [ArchNodeType.PAYMENT_GATEWAY]: 'Payment Gateway',
  [ArchNodeType.NOTIFICATION_SERVICE]: 'Notification Service',
  [ArchNodeType.ANALYTICS_SERVICE]: 'Analytics Service',
  [ArchNodeType.REAL_TIME_DB]: 'Real-time Database',
};
